name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print working directory and list files
        run: |
          echo "Current Directory: $(pwd)"
          ls -R

      - name: Verify package-lock.json presence
        run: |
          if [ -f "qr-code/package-lock.json" ]; then
            echo "package-lock.json found in qr-code"
          else
            echo "package-lock.json not found in qr-code"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        env:
          npm_config_cache: "${{ github.workspace }}/qr-code/.npm"

      - name: Install dependencies
        run: npm ci
        working-directory: qr-code

      - name: Build Next.js application
        run: npx next build
        working-directory: qr-code

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: qr-code/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
